version: '3'
services:  
  arm64:
    image: 'nacos/nacos-server:v2.1.0-slim'
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - MODE=standalone