version: '3'
services:
  instanse:
    image: 'rabbitmq:3-management'
    restart: always
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672
      - 15671:15671
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=1qazZAQ!123
      - TZ=Asia/Shanghai
