version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=1qazZAQ!
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

