version: '3'
services:
  geoserver:
    image: 'geonode/geoserver'
    restart: always
    ports:
      - 8124:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/geoserver/data:/geoserver_data/data
