version: '3'
services:
  postgre:
    image: postgis/postgis
    restart: always
    container_name: postgre
    environment:
      - POSTGRES_PASSWORD=1qazZAQ!
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    volumes:
      - ~/docker_data/postgre:/var/lib/postgresql/data/pgdata
      - ./default.conf:/etc/postgresql/postgresql.conf
