FROM thinkwhere/geoserver:2.18

RUN apt-get update
RUN deb http://us.archive.ubuntu.com/ubuntu/ lucid multiverse
RUN deb-src http://us.archive.ubuntu.com/ubuntu/ lucid multiverse
RUN deb http://us.archive.ubuntu.com/ubuntu/ lucid-updates multiverse
RUN deb-src http://us.archive.ubuntu.com/ubuntu/ lucid-updates multiverse
RUN apt-get install ttf-mscorefonts-installer