version: '3'
services: 
  elasticsearch:
    image: 'elasticsearch:7.10.1'
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - TZ=Asia/Shanghai
    volumes:
      - ~/data/elasticsearch/data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2048M