version: "3"
services:
  zentao:
    image: registry.cn-shanghai.aliyuncs.com/zlzforever/zentao
    restart: always
    ports:
      - "8013:80"
    volumes:
      - /data/data/zentao/pms:/app/zentaopms
      - /data/data/zentao/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1qazZAQ!