version: '3'
services:
  instanse:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=1qazZAQ!"
      - "MSSQL_PID=Express"
