version: '3'
services:
  amd64:
    image: 'mysql:8'
    restart: always
    platform: linux/amd64
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1qazZAQ!
      - TZ=Asia/Shanghai
    volumes:
      # - ./conf.d:/etc/mysql/conf.d
      - ~/docker_data/mysql:/var/lib/mysql
  arm64:
    image: 'mysql/mysql-server:8.0'
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1qazZAQ!
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_HOST='%'
    volumes:
      - ~/docker_data/mysql_arm64:/var/lib/mysql
